### PR TITLE
0.3.0 merge to latest 

### PR DESCRIPTION
**Pull request by spencercap**
- adds `any-wallet` under the hood 
- iframe comms fixes
- + so much more 

- [x] dont forget to switch default src to inkey.app/ instead of staging url (https://github.com/thencc/any-wallet/issues/13)

related issues:
- https://github.com/thencc/algonautjs/issues/2
- https://github.com/thencc/algonautjs/issues/68
- https://github.com/thencc/algonautjs/issues/67
- https://github.com/thencc/algonautjs/issues/64
- https://github.com/thencc/algonautjs/issues/55
- https://github.com/thencc/algonautjs/issues/54
- https://github.com/thencc/algonautjs/issues/49
- https://github.com/thencc/algonautjs/issues/48
- https://github.com/thencc/algonautjs/issues/47
- https://github.com/thencc/algonautjs/issues/41
- https://github.com/thencc/algonautjs/issues/35

### CODE REVIEW

**Comment by spencercap** [comment]
BEFORE MERGE!!!

don't forget to update `any-wallet`'s default inkey-client-js src to the LIVE inkey.app/ site instead of the staging domain

**Comment by spencercap** [comment]
still needs a readme update but...

a bunch o goodies were brought back by popular demand like: 
- .inkeyShow 
- .inkeyHide 
- .connect() 
- - now takes a single wallet's init params
- etc

**Comment by enceladus** [comment]
A few methods were renamed? A bit confusing.  

```
fromBase64 --> b64StrToHumanStr
to8Arr --> toUint8Array
```

When doing this in the future, please leave the original methods & mark as deprecated! This will make upgrading everything that depends on algonautjs _so much easier_.

**Comment by spencercap** [comment]
yes yes, you're right. sorry about that @enceladus 

was trying to make the names more helpful and not leave in what were confusing to me. moving forward should we keep both functional, the former marked as deprecated and then remove it completely in a larger point release?

**Comment by spencercap** [comment]
@youraerials 
are we going ahead w depending on our custom algosdk fork?

**Pull request merged**
